### ISSUE TITLE
Timestamps displayed in synced lyrics

### ISSUE THREAD

**Issue by fwn0** [ESLyric/feedback#41] opened 2022-11-12 14:16 UTC
Hi ohyeah,

I have sometimes problems with synced lyric files on Linux/Wine when displaying the lyrics.
I've tried with encoding settings UTF8 +BOM and also ANSI. It looks like this:

![fb-lyrics](https://user-images.githubusercontent.com/35877841/201477981-edad5446-ce64-47cd-94bd-613d9ed39482.jpg)

This happens only on some fetched lyrics but not all the time...

Thanks for your work on this component!

**Comment by ESLyric** [comment] 2022-11-12 15:23
It's a ESLyric panel? if so, please upload this lyric file.

**Comment by TT-ReBORN** [comment] 2022-11-12 16:11
Yea, it's a problem with the synced lyric file. If you open it you will see the additional timestamps...
Just checked, this is not a Linux/Wine issue but on Windows it's the same.

Here is the synced lyric file:
https://cloud.multibits.eu/s/pc9fQLCZj6bEx55

-TT

**Comment by ESLyric** [comment] 2022-11-12 17:47
it looks fine here. make sure you are using the latest eslyric.(0.3.x cannot display correctly.)
![image](https://user-images.githubusercontent.com/102273569/201487487-3a0c1084-109f-4962-8aaa-9fe500d9510e.png)

**Comment by TT-ReBORN** [comment] 2022-11-12 18:27
Yeah, I'm using the latest version. Actually I only use your component for fetching lyrics.

I have my own lyric script that displays the fetched lyrics and use ESLyric as a hidden panel in the Columns UI layout.
You can check for yourself my theme [here](https://cloud.multibits.eu/s/nzWiQe5bkDMxLdS). Just install a new portable foobar and drag and drop the profile folder in foobar's root directory. If you drag and drop the song into the playlist and click on the top menu button Lyrics, it will use your component to fetch the lyrics that will be saved to HDD and then automatically displayed. You can also right click for context menu > Lyrics options menu where you can find some of your ESLyric options.

The lyrics code for the theme is written in gr-lyrics.js.
As I've written, this happens only sometimes not all the time. I think the problem is the lyric source and how the text is parsed into the lyric file...

Thanks for your help

-TT

**Comment by ESLyric** [comment] 2022-11-12 18:53
Your js code must support it. See [LRC(file_format)](https://en.wikipedia.org/wiki/LRC_(file_format))
esl may fetch multi-timestamps lyrics from some sources, e.g kugou.js or qqmusic.js, and currently there is no option to retrieve standard lyric format only(nor save it as standard lyric format).

**Comment by TT-ReBORN** [comment] 2022-11-12 19:07
Ah got it! I did not know about the enhanced extension for the lrc format, thanks for letting me know!
Any tips for js implementation? I'll take a look how to do it, you can also close this as everything is OK.

**Comment by ESLyric** [comment] 2022-11-12 19:23
It's ok just remove `<xx.xx.xx>` tags using regex.

**Comment by TT-ReBORN** [comment] 2022-11-12 19:36
Got it, just used `.replace(/(\s*)<(\d{1,2}:|)\d{1,2}:\d{2}(>|\.\d{1,3}>)(\s*)/g, ' ');` and everything is fine!
I'll credit you for your component on the main Georgia-ReBORN Github site once I've released the first public release,
ESLyric works much better ( also great on Linux/Wine ) than the old Lyric Show 3 component!

Thanks for your work!

-TT

**Comment by ESLyric** [comment] 2022-11-13 03:42
Thanks, I'll appreciate it.

**Closed by ESLyric** 2022-11-13 03:42 UTC
